# Project language
language: php
php:
  - 7.3.24

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Define an environment variable
env:
  - DB=mysql

# Update composer
before-install:
  - composer self-update

# Install composer dependencies,
# Create database, schema and fixtures
install:
  - composer install
  - php bin/console doctrine:database:create
  - php bin/console doctrine:schema:create
  - php bin/console doctrine:fixtures:load

# Run script
script:
  - phpunit